services:
  postgres:
    image: postgres:14
    container_name: backend-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: prueba_backend
    ports:
      - "5433:5432"
    volumes:
      - backend_pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  backend_pgdata: